# Generated by Django 2.1.5 on 2019-01-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='category', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='US', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default='2020-2-20'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='launched',
            field=models.DateTimeField(default='2020-2-20 12:12:12'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_category',
            field=models.CharField(default='sure', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='ok', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pledged',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default='fine', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='usd_goal_real',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='usd_pledged',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='usd_pledged_real',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
