# Generated by Django 2.1.5 on 2019-01-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0002_auto_20190114_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backers',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(default='cat', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(default='country', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_category',
            field=models.CharField(default='maincat', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='name', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='pledged',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(default='state', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='usd_goal_real',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='usd_pledged',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='usd_pledged_real',
            field=models.FloatField(default='0.0'),
        ),
    ]
