# Generated by Django 2.1.5 on 2019-01-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0003_auto_20190115_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='backers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='launched',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pledged',
        ),
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usd_goal_real',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usd_pledged',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usd_pledged_real',
        ),
    ]
