# Generated by Django 2.1.5 on 2019-01-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0006_auto_20190116_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backers',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='cat', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='country', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default='2020-2-20'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='project',
            name='launched',
            field=models.DateTimeField(default='2020-2-20 12:12:12'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_category',
            field=models.CharField(default='maincat', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='pledged',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default='state', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='usd_goal_real',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='project',
            name='usd_pledged',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='project',
            name='usd_pledged_real',
            field=models.FloatField(default='0.0'),
        ),
    ]
