# Generated by Django 2.1.5 on 2019-01-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0007_auto_20190116_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backers',
            field=models.IntegerField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.FloatField(default='0.0', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='pledged',
            field=models.FloatField(default='0.0', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='usd_goal_real',
            field=models.FloatField(default='0.0', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='usd_pledged',
            field=models.FloatField(default='0.0', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='usd_pledged_real',
            field=models.FloatField(default='0.0', max_length=64),
        ),
    ]
