# Generated by Django 2.1.5 on 2019-01-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0009_auto_20190116_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
    ]
