# Generated by Django 2.1.5 on 2019-01-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0011_auto_20190116_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=64),
        ),
    ]
