# Generated by Django 2.1.5 on 2019-01-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0012_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='country', max_length=64),
        ),
    ]
